---
abstract: "Perl interface to the GitHub's pastebin service"
author:
  - 'Alessandro Ghedini <alexbio@cpan.org>'
build_requires:
  File::Find: 0
  File::Temp: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300021, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: WWW-GitHub-Gist
requires:
  Carp: 0
  HTTP::Tiny: 0
  JSON: 0
  MIME::Base64: 0
  Moo: 0
  base: 0
  strict: 0
  warnings: 0
resources:
  bugtracker: https://github.com/ghedo/p5-WWW-GitHub-Gist/issues
  homepage: http://metacpan.org/release/WWW-GitHub-Gist/
  repository: git://github.com/ghedo/p5-WWW-GitHub-Gist.git
version: 0.17
x_Dist_Zilla:
  plugins:
    -
      class: Dist::Zilla::Plugin::GatherDir
      name: '@Filter/GatherDir'
      version: 4.300021
    -
      class: Dist::Zilla::Plugin::PruneCruft
      name: '@Filter/PruneCruft'
      version: 4.300021
    -
      class: Dist::Zilla::Plugin::ManifestSkip
      name: '@Filter/ManifestSkip'
      version: 4.300021
    -
      class: Dist::Zilla::Plugin::MetaYAML
      name: '@Filter/MetaYAML'
      version: 4.300021
    -
      class: Dist::Zilla::Plugin::License
      name: '@Filter/License'
      version: 4.300021
    -
      class: Dist::Zilla::Plugin::Readme
      name: '@Filter/Readme'
      version: 4.300021
    -
      class: Dist::Zilla::Plugin::ExtraTests
      name: '@Filter/ExtraTests'
      version: 4.300021
    -
      class: Dist::Zilla::Plugin::ExecDir
      name: '@Filter/ExecDir'
      version: 4.300021
    -
      class: Dist::Zilla::Plugin::ShareDir
      name: '@Filter/ShareDir'
      version: 4.300021
    -
      class: Dist::Zilla::Plugin::Manifest
      name: '@Filter/Manifest'
      version: 4.300021
    -
      class: Dist::Zilla::Plugin::TestRelease
      name: '@Filter/TestRelease'
      version: 4.300021
    -
      class: Dist::Zilla::Plugin::ConfirmRelease
      name: '@Filter/ConfirmRelease'
      version: 4.300021
    -
      class: Dist::Zilla::Plugin::MakeMaker
      name: '@Filter/MakeMaker'
      version: 4.300021
    -
      class: Dist::Zilla::Plugin::GitHub::Meta
      name: '@Filter/@GitHub/GitHub::Meta'
      version: 0.27
    -
      class: Dist::Zilla::Plugin::GitHub::Update
      name: '@Filter/@GitHub/GitHub::Update'
      version: 0.27
    -
      class: Dist::Zilla::Plugin::Git::NextVersion
      name: '@Filter/Git::NextVersion'
      version: 1.121820
    -
      class: Dist::Zilla::Plugin::MetaConfig
      name: '@Filter/MetaConfig'
      version: 4.300021
    -
      class: Dist::Zilla::Plugin::MetaJSON
      name: '@Filter/MetaJSON'
      version: 4.300021
    -
      class: Dist::Zilla::Plugin::PodVersion
      name: '@Filter/PodVersion'
      version: 4.300021
    -
      class: Dist::Zilla::Plugin::PkgVersion
      name: '@Filter/PkgVersion'
      version: 4.300021
    -
      class: Dist::Zilla::Plugin::ChangelogFromGit
      name: '@Filter/ChangelogFromGit'
      version: 0.005
    -
      class: Dist::Zilla::Plugin::Test::Compile
      name: '@Filter/Test::Compile'
      version: 1.112820
    -
      class: Dist::Zilla::Plugin::Test::CheckManifest
      name: '@Filter/Test::CheckManifest'
      version: 0.04
    -
      class: Dist::Zilla::Plugin::PodSyntaxTests
      name: '@Filter/PodSyntaxTests'
      version: 4.300021
    -
      class: Dist::Zilla::Plugin::PodCoverageTests
      name: '@Filter/PodCoverageTests'
      version: 4.300021
    -
      class: Dist::Zilla::Plugin::Git::Tag
      name: '@Filter/Git::Tag'
      version: 1.121820
    -
      class: Dist::Zilla::Plugin::Git::Push
      name: '@Filter/Git::Push'
      version: 1.121820
    -
      class: Dist::Zilla::Plugin::UploadToCPAN
      name: '@Filter/UploadToCPAN'
      version: 4.300021
    -
      class: Dist::Zilla::Plugin::InstallRelease
      name: '@Filter/InstallRelease'
      version: 0.008
    -
      class: Dist::Zilla::Plugin::Clean
      name: '@Filter/Clean'
      version: 0.07
    -
      class: Dist::Zilla::Plugin::AutoPrereqs
      name: AutoPrereqs
      version: 4.300021
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':InstallModules'
      version: 4.300021
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':IncModules'
      version: 4.300021
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':TestFiles'
      version: 4.300021
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ExecFiles'
      version: 4.300021
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ShareFiles'
      version: 4.300021
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':MainModule'
      version: 4.300021
  zilla:
    class: Dist::Zilla::Dist::Builder
    config:
      is_trial: 0
    version: 4.300021
